# Generated by Django 5.1.3 on 2024-12-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
